{{- if .Values.addons.argocd.enabled  }}
{{ include "incloud-web-resources.factory.manifets.argocd-application-details" (dict
  "key" "argocd-application-details"
  "resName" "{6}"
) }}

{{- if not .Values.namespaceNavigation }}
{{ include "incloud-web-resources.factory.manifets.argocd-application-details" (dict
  "key" "instance-argocd-application-details"
  "resName" "{7}"
) }}
{{- end }}
{{- end }}
