{{ include "incloud-web-resources.factory.manifets.configmap-details" (dict
  "key" "configmap-details"
  "resName" "{6}"
  "basePrefix" .Values.basePrefix
) }}

{{ include "incloud-web-resources.factory.manifets.configmap-details" (dict
  "key" "instance-configmap-details"
  "resName" "{7}"
  "basePrefix" .Values.basePrefix
) }}
