{{ include "incloud-web-resources.factory.manifets.deployment-details" (dict
  "key" "deployment-details"
  "resName" "{6}"
  "rsFactoryName" "stock-namespace-/apps/v1/replicasets"
  "podFactoryName" "stock-namespace-/v1/pods"
  "basePrefix" .Values.basePrefix
) }}

{{- if not .Values.namespaceNavigation }}
{{ include "incloud-web-resources.factory.manifets.deployment-details" (dict
  "key" "instance-deployment-details"
  "resName" "{7}"
  "rsFactoryName" "stock-namespace-/apps/v1/replicasets"
  "podFactoryName" "stock-namespace-/v1/pods"
  "basePrefix" .Values.basePrefix
) }}
{{- end }}
