{{ include "incloud-web-resources.factory.manifets.deployment-details" (dict
  "key" "deployment-details"
  "resName" "{6}"
  "rsFactoryName" "factory-/apps/v1/replicasets"
  "podFactoryName" "factory-/v1/pods"
) }}

{{- if not .Values.namespaceNavigation }}
{{ include "incloud-web-resources.factory.manifets.deployment-details" (dict
  "key" "instance-deployment-details"
  "resName" "{7}"
  "rsFactoryName" "factory-instance-replicaset-details"
  "podFactoryName" "factory-instance-pods-details"
) }}
{{- end }}
