---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-cluster-v1.configmaps"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "CM"
      "title" "ConfigMap"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "configmap-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Namespace"
      "text" "N"
      "title" "Namespace"
      "backgroundColor" "#a25792ff"
      "reqIndex" 0
      "type" "namespace"
      "jsonPath" ".metadata.namespace"
      "factory" "namespace-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  additionalPrinterColumnsUndefinedValues:
    - key: Namespace
      value: "-"
  id: "stock-cluster-/v1/configmaps"

{{ if .Values.namespaceNavigation }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-namespace-v1.configmaps"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "CM"
      "title" "ConfigMap"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "configmap-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  id: "stock-namespace-/v1/configmaps"
{{ else }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-project-v1.configmaps"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "CM"
      "title" "ConfigMap"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "configmap-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  id: "stock-project-/v1/configmaps"

---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "stock-instance-v1.configmaps"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "CM"
      "title" "ConfigMap"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "project" "{4}"
      "factory" "instance-configmap-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  id: "stock-instance-/v1/configmaps"
{{ end }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: CustomColumnsOverride
metadata:
  name: "cluster-v1.configmaps"
spec:
  additionalPrinterColumns:
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Name"
      "text" "CM"
      "title" "ConfigMap"
      "backgroundColor" "#b48c78ff"
      "reqIndex" 0
      "type" "name"
      "jsonPath" ".metadata.name"
      "namespace" "{reqsJsonPath[0]['.metadata.namespace']['-']}"
      "factory" "configmap-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.icon-link-block" (dict
      "columnName" "Namespace"
      "text" "N"
      "title" "Namespace"
      "backgroundColor" "#a25792ff"
      "reqIndex" 0
      "type" "namespace"
      "jsonPath" ".metadata.namespace"
      "factory" "namespace-details"
      "basePrefix" .Values.basePrefix
    ) | nindent 4
    }}
    {{ include "incloud-web-resources.cco.columns.timeblock" (dict
      "columnName" "Created"
      "jsonPath" ".metadata.creationTimestamp"
    ) | nindent 4
    }}
  additionalPrinterColumnsTrimLengths:
    {{ include "incloud-web-resources.cco.columns-trim-lengths.name" . | nindent 4 }}
  additionalPrinterColumnsUndefinedValues:
    - key: Namespace
      value: "-"
  id: "cluster-/v1/configmaps"
