---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-project-factory-deployment-details
spec:
  id: "stock-project-factory-deployment-details"
  breadcrumbItems:
    - key: deployments
      label: "apps/v1/deployments"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/api-table/apps/v1/deployments"
    - key: Deployment
      label: "{9}"

{{- if not .Values.namespaceNavigation }}
---
apiVersion: front.in-cloud.io/v1alpha1
kind: Breadcrumb
metadata:
  name: stock-instance-factory-instance-deployment-details
spec:
  id: "stock-instance-factory-instance-deployment-details"
  breadcrumbItems:
    - key: deployments
      label: "apps/v1/deployments"
      link: "/{{ .Values.basePrefix }}/{cluster}/{namespace}/{syntheticProject}/api-table/apps/v1/deployments"
    - key: Deployment
      label: "{10}"
{{- end -}}
